#!/usr/bin/env bash
#
# OpenVPN Installation Script for Marzneshin/Marznode
# Automatically installs and configures OpenVPN server
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
OPENVPN_PORT=${OPENVPN_PORT:-1194}
OPENVPN_PROTO=${OPENVPN_PROTO:-udp}
OPENVPN_NETWORK=${OPENVPN_NETWORK:-10.8.0.0}
OPENVPN_NETMASK=${OPENVPN_NETMASK:-255.255.255.0}
OPENVPN_DATA_DIR="/var/lib/marznode/openvpn"
OPENVPN_CONFIG_DIR="/etc/openvpn"
OPENVPN_LOG_FILE="/var/log/openvpn.log"
OPENVPN_CONNECTIONS_LOG="/var/log/openvpn-connections.log"

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [ "$(id -u)" != "0" ]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
    elif [ -f /etc/lsb-release ]; then
        OS=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
    else
        log_error "Cannot detect operating system"
        exit 1
    fi
    
    log_info "Detected OS: $OS"
}

install_package() {
    case $OS in
        ubuntu|debian)
            apt-get update
            apt-get install -y "$1"
            ;;
        centos|almalinux|rocky)
            yum install -y "$1"
            ;;
        fedora)
            dnf install -y "$1"
            ;;
        arch)
            pacman -S --noconfirm "$1"
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
}

check_openvpn_installed() {
    if command -v openvpn &> /dev/null; then
        log_warning "OpenVPN is already installed"
        read -p "Do you want to reinstall? (y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        fi
    fi
}

install_openvpn() {
    log_info "Installing OpenVPN..."
    
    case $OS in
        ubuntu|debian)
            apt-get update
            apt-get install -y openvpn easy-rsa openssl
            ;;
        centos|almalinux|rocky)
            yum install -y epel-release
            yum install -y openvpn easy-rsa openssl
            ;;
        fedora)
            dnf install -y openvpn easy-rsa openssl
            ;;
        arch)
            pacman -S --noconfirm openvpn easy-rsa openssl
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
    
    log_success "OpenVPN installed"
}

create_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$OPENVPN_DATA_DIR"/{certs,configs,ccd}
    mkdir -p "$OPENVPN_CONFIG_DIR"/easy-rsa
    mkdir -p /var/log
    
    touch "$OPENVPN_LOG_FILE"
    touch "$OPENVPN_CONNECTIONS_LOG"
    
    chmod 666 "$OPENVPN_CONNECTIONS_LOG"
    
    log_success "Directories created"
}

setup_pki() {
    log_info "Setting up PKI (Public Key Infrastructure)..."
    
    # Copy Easy-RSA
    if [ -d /usr/share/easy-rsa ]; then
        cp -r /usr/share/easy-rsa/* "$OPENVPN_CONFIG_DIR/easy-rsa/"
    elif [ -d /usr/share/doc/easy-rsa ]; then
        cp -r /usr/share/doc/easy-rsa/* "$OPENVPN_CONFIG_DIR/easy-rsa/"
    else
        log_error "Easy-RSA not found"
        exit 1
    fi
    
    cd "$OPENVPN_CONFIG_DIR/easy-rsa"
    
    # Initialize PKI
    ./easyrsa init-pki
    
    # Build CA (non-interactive)
    ./easyrsa build-ca nopass
    
    # Generate server certificate
    ./easyrsa build-server-full server nopass
    
    # Generate Diffie-Hellman parameters
    log_info "Generating Diffie-Hellman parameters (this may take a few minutes)..."
    ./easyrsa gen-dh
    
    # Copy files to OpenVPN directory
    cp pki/ca.crt "$OPENVPN_CONFIG_DIR/"
    cp pki/issued/server.crt "$OPENVPN_CONFIG_DIR/"
    cp pki/private/server.key "$OPENVPN_CONFIG_DIR/"
    cp pki/dh.pem "$OPENVPN_CONFIG_DIR/dh2048.pem"
    
    # Generate TLS auth key
    openvpn --genkey --secret "$OPENVPN_CONFIG_DIR/ta.key"
    
    log_success "PKI setup complete"
}

create_server_config() {
    log_info "Creating server configuration..."
    
    cat > "$OPENVPN_CONFIG_DIR/server.conf" <<EOF
# OpenVPN Server Configuration for Marzneshin
# Generated by install-openvpn.sh

port $OPENVPN_PORT
proto $OPENVPN_PROTO
dev tun

# Certificate paths
ca $OPENVPN_CONFIG_DIR/ca.crt
cert $OPENVPN_CONFIG_DIR/server.crt
key $OPENVPN_CONFIG_DIR/server.key
dh $OPENVPN_CONFIG_DIR/dh2048.pem
tls-auth $OPENVPN_CONFIG_DIR/ta.key 0

# Network settings
server $OPENVPN_NETWORK $OPENVPN_NETMASK
topology subnet
ifconfig-pool-persist $OPENVPN_DATA_DIR/ipp.txt

# Client-specific configuration directory
client-config-dir $OPENVPN_DATA_DIR/ccd

# Logging
status $OPENVPN_DATA_DIR/openvpn-status.log
status-version 2
log-append $OPENVPN_LOG_FILE
verb 3

# Keep alive
keepalive 10 120

# Security
cipher AES-256-GCM
auth SHA256

# Persist settings
persist-key
persist-tun

# User management scripts for Marznode tracking
script-security 2
client-connect $OPENVPN_DATA_DIR/client-connect.sh
client-disconnect $OPENVPN_DATA_DIR/client-disconnect.sh

# Max clients
max-clients 1000

# Compression (disabled for security)
;comp-lzo

# User/group (uncomment for production)
;user nobody
;group nogroup
EOF
    
    log_success "Server configuration created"
}

create_management_scripts() {
    log_info "Creating management scripts..."
    
    # Client connect script
    cat > "$OPENVPN_DATA_DIR/client-connect.sh" <<'EOF'
#!/bin/bash
# Client connect script for Marznode

logger="logger -t openvpn-marznode"

# Get client common name (format: userid.username)
CN="$common_name"
USER_ID=$(echo "$CN" | cut -d'.' -f1)

$logger "Client connect: CN=$CN, User ID=$USER_ID, IP=$trusted_ip"

# Write connection event to tracking file
echo "CONNECT|$CN|$trusted_ip|$(date +%s)" >> /var/log/openvpn-connections.log
EOF
    
    chmod +x "$OPENVPN_DATA_DIR/client-connect.sh"
    
    # Client disconnect script
    cat > "$OPENVPN_DATA_DIR/client-disconnect.sh" <<'EOF'
#!/bin/bash
# Client disconnect script for Marznode

logger="logger -t openvpn-marznode"

CN="$common_name"
USER_ID=$(echo "$CN" | cut -d'.' -f1)
BYTES_RECV=$bytes_received
BYTES_SENT=$bytes_sent

$logger "Client disconnect: CN=$CN, User ID=$USER_ID, Received=$BYTES_RECV, Sent=$BYTES_SENT"

# Write disconnection event with bandwidth
echo "DISCONNECT|$CN|$BYTES_RECV|$BYTES_SENT|$(date +%s)" >> /var/log/openvpn-connections.log
EOF
    
    chmod +x "$OPENVPN_DATA_DIR/client-disconnect.sh"
    
    log_success "Management scripts created"
}

setup_firewall() {
    log_info "Configuring firewall..."
    
    # Enable IP forwarding
    if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p
    fi
    
    # Configure firewall based on what's available
    if command -v ufw &> /dev/null; then
        ufw allow $OPENVPN_PORT/$OPENVPN_PROTO
        ufw allow OpenSSH
        log_success "UFW firewall configured"
    elif command -v firewall-cmd &> /dev/null; then
        firewall-cmd --permanent --add-port=$OPENVPN_PORT/$OPENVPN_PROTO
        firewall-cmd --permanent --add-service=ssh
        firewall-cmd --reload
        log_success "Firewalld configured"
    elif command -v iptables &> /dev/null; then
        iptables -A INPUT -p $OPENVPN_PROTO --dport $OPENVPN_PORT -j ACCEPT
        iptables -t nat -A POSTROUTING -s $OPENVPN_NETWORK/$OPENVPN_NETMASK -o eth0 -j MASQUERADE
        log_success "iptables configured"
    else
        log_warning "No firewall detected, manual configuration may be needed"
    fi
}

setup_systemd() {
    log_info "Setting up systemd service..."
    
    # Create systemd service if it doesn't exist
    if [ ! -f /etc/systemd/system/openvpn@server.service ]; then
        cat > /etc/systemd/system/openvpn@server.service <<EOF
[Unit]
Description=OpenVPN service using %i configuration
After=network-online.target

[Service]
Type=notify
ExecStart=/usr/sbin/openvpn --config /etc/openvpn/%i.conf
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
        
        systemctl daemon-reload
    fi
    
    # Enable and start service
    systemctl enable openvpn@server
    systemctl start openvpn@server
    
    log_success "Systemd service configured"
}

configure_marznode() {
    log_info "Configuring Marznode for OpenVPN..."
    
    MARZNODE_ENV_FILE="/var/lib/marznode/.env"
    
    # Create or update Marznode .env file
    if [ ! -f "$MARZNODE_ENV_FILE" ]; then
        mkdir -p "$(dirname "$MARZNODE_ENV_FILE")"
        touch "$MARZNODE_ENV_FILE"
    fi
    
    # Add OpenVPN configuration if not present
    if ! grep -q "OPENVPN_ENABLED" "$MARZNODE_ENV_FILE"; then
        cat >> "$MARZNODE_ENV_FILE" <<EOF

# OpenVPN Configuration (added by install-openvpn.sh)
OPENVPN_ENABLED=true
OPENVPN_EXECUTABLE_PATH=/usr/sbin/openvpn
OPENVPN_CONFIG_PATH=/etc/openvpn/server.conf
OPENVPN_DATA_DIR=/var/lib/marznode/openvpn
EOF
        log_success "Marznode environment configured"
    else
        log_warning "Marznode already has OpenVPN configuration"
    fi
}

verify_installation() {
    log_info "Verifying installation..."
    
    # Check if OpenVPN is running
    if systemctl is-active --quiet openvpn@server; then
        log_success "OpenVPN service is running"
    else
        log_warning "OpenVPN service is not running"
        log_info "Starting OpenVPN service..."
        systemctl start openvpn@server
    fi
    
    # Check if status file exists
    sleep 2
    if [ -f "$OPENVPN_DATA_DIR/openvpn-status.log" ]; then
        log_success "Status file created"
    else
        log_warning "Status file not found yet"
    fi
    
    # Show server info
    echo ""
    log_success "OpenVPN installation complete!"
    echo ""
    echo "Server Configuration:"
    echo "  Port: $OPENVPN_PORT"
    echo "  Protocol: $OPENVPN_PROTO"
    echo "  Network: $OPENVPN_NETWORK/$OPENVPN_NETMASK"
    echo ""
    echo "Important Files:"
    echo "  Server Config: $OPENVPN_CONFIG_DIR/server.conf"
    echo "  CA Certificate: $OPENVPN_CONFIG_DIR/ca.crt"
    echo "  Status Log: $OPENVPN_DATA_DIR/openvpn-status.log"
    echo "  Connections Log: $OPENVPN_CONNECTIONS_LOG"
    echo ""
    echo "Next Steps:"
    echo "  1. Restart Marznode to enable OpenVPN backend"
    echo "  2. Add OpenVPN inbound in Marzneshin panel"
    echo "  3. Create users and download .ovpn configs"
    echo ""
}

# Main installation function
main() {
    echo "=========================================="
    echo "  OpenVPN Installation for Marzneshin"
    echo "=========================================="
    echo ""
    
    check_root
    detect_os
    check_openvpn_installed
    install_openvpn
    create_directories
    setup_pki
    create_server_config
    create_management_scripts
    setup_firewall
    setup_systemd
    configure_marznode
    verify_installation
    
    log_success "Installation completed successfully!"
}

# Parse command line arguments
case "${1:-install}" in
    install)
        main
        ;;
    uninstall)
        log_info "Uninstalling OpenVPN..."
        systemctl stop openvpn@server || true
        systemctl disable openvpn@server || true
        rm -rf "$OPENVPN_CONFIG_DIR"
        rm -rf "$OPENVPN_DATA_DIR"
        apt-get remove --purge -y openvpn easy-rsa 2>/dev/null || yum remove -y openvpn easy-rsa 2>/dev/null || true
        log_success "OpenVPN uninstalled"
        ;;
    status)
        systemctl status openvpn@server
        ;;
    logs)
        tail -f "$OPENVPN_LOG_FILE"
        ;;
    *)
        echo "Usage: $0 {install|uninstall|status|logs}"
        exit 1
        ;;
esac
